"""Add type column to user notification table

Revision ID: 2e4997630727
Revises: 5bedad46562c
Create Date: 2022-04-06 11:48:43.975722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4997630727'
down_revision = '5bedad46562c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'usernotifications', sa.Column('notfication_type', sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usernotifications', 'notfication_type')
    # ### end Alembic commands ###
